name: Hprofile Actions
# on branch
on: workflow_dispatch
# provide region in workflow or in secrets
env:
  AWS_REGION: us-east-1
jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      # using hprofile specific directory
      run:
        working-directory: ./hprofile-project-github-actions/hprofile-main
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      # Setup multiple Java versions (11 and 17)
      - name: Setup Java versions
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: |
            11
            17

      # explicitly switch to Java 11
      - name: Maven Test
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          mvn test

      # checkstyle using java 11
      - name: Checkstyle
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          mvn checkstyle:checkstyle

      # setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v8

      # sonarQube Scan using java 17
      - name: SonarQube Scan
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL

  # building and publishing docker image
  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      # search and replace database information
      - name: Update Application.properties File
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          sed -i 's|^jdbc.username=.*|jdbc.username=${{ secrets.RDS_USER }}|' hprofile-project-github-actions/hprofile-main/src/main/resources/application.properties
          sed -i 's|^jdbc.password=.*|jdbc.password=${{ secrets.RDS_PASS }}|' hprofile-project-github-actions/hprofile-main/src/main/resources/application.properties
          sed -i 's|db01|${{ secrets.RDS_ENDPOINT }}|g' hprofile-project-github-actions/hprofile-main/src/main/resources/application.properties

      # building docker images
      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: actions-app
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          daemon_off: false
          dockerfile: ./hprofile-project-github-actions/hprofile-main/Dockerfile
          context: ./hprofile-project-github-actions/hprofile-main/