name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hprofile-project-github-actions/hprofile-main
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      # Setup multiple Java versions (11 and 17)
      - name: Setup Java versions
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: |
            11
            17

      # Maven commands will use Java 17 (the last one in the list)
      # So we need to explicitly switch to Java 11
      - name: Maven Test
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          mvn test

      - name: Checkstyle
        run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          mvn checkstyle:checkstyle

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v8

      # SonarQube Scan with Java 17
      - name: SonarQube Scan
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          sonar-scanner \
           -Dsonar.host.url=${{ secrets.SONAR_URL }} \
           -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
           -Dsonar.sources=src/ \
           -Dsonar.junit.reportsPath=target/surefire-reports/ \
           -Dsonar.jacoco.reportsPath=target/jacoco.exec \
           -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml \
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
