name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      # set java versions
      - name: Set Java Versions
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # distribution
          java-version: |
                        11
                        17

      # running maven command
      - name: Maven Test
        working-directory: ./hprofile-project-github-actions/hprofile-main
        run: |
            export JAVA_HOME=$JAVA_HOME_11_X64
            mvn test

      - name: Checkstyle
        working-directory: ./hprofile-project-github-actions/hprofile-main
        run: |
            export JAVA_HOME=$JAVA_HOME_11_X64
            mvn checkstyle:checkstyle

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v8

      # Run sonar-scanner
      - name: SonarQube Scan
        working-directory: ./hprofile-project-github-actions/hprofile-main
        run: |
            export JAVA_HOME=$JAVA_HOME_17_X64
            sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account \
